version: '3.8'

services:

  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro
      MYSQL_USER: usr
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5

  node-app:
    build:
      context: .
    image: markosdjs/node-app
    entrypoint: sh -c "npm install && node index.js"
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    networks:
      - proxy-network
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-network
    depends_on:
      - node-app

networks:
  proxy-network:
    driver: bridge
volumes:
  db_data:
    driver: local