version: '3.8'

services:

  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro
      MYSQL_USER: usr
      MYSQL_PASSWORD: root
    
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ../temp/db_data/mysql:/var/lib/mysql
    networks:
      - proxy-network

  node-app:
    build:
      context: .
    image: markosdjs/node-app
    container_name: node-app
    working_dir: /usr/src/app
    networks:
      - proxy-network
    depends_on:
      - database
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-network
    depends_on:
      - node-app

networks:
  proxy-network:
    driver: bridge